name: Schemas Should Be Unique
on: [push]
jobs:
  Check-Schema-Uniqueness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Get dupes
        id: dupes
        run: |
          echo "found_dupes=$(find schema ! -empty -type f -exec basename {} \; -exec sh -c 'md5sum "$1"' _ {} \; | sort | uniq -dD | xargs)" >> $GITHUB_OUTPUT
      - name: Comment PR Found
        uses: thollander/actions-comment-pull-request@v2
        if: steps.dupes.outputs.found_dupes
        with:
          message: |
            :warning: Potentially found duplicate schema names!