name: Schemas Should Be Unique
on: [push]
jobs:
  Check-Schema-Uniqueness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Get changed files
        id: changed-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
              echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          else
              echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          fi
      - name: List files in the repository  # this wont' work because all-schemas will have pr schemas too
        id: all-schemas
        run: |
          echo "all_schemas=$(find schema -type f -exec basename {} \; | xargs)" >> $GITHUB_OUTPUT
      - name: Show all-schemas output for debugging
        run: | # WHY ISNT ECHO WORKING
          echo 'outputs are: ${{ (steps.all-schemas.outputs.*) }}'
        shell:
          bash
      - name: Show changed-files output for debugging
        run: |
          echo 'outputs are: ${{ (steps.changed-files.outputs.*) }}'
        shell:
          bash
      - name: Find dupes
        id: find-dupes
        run: |
          for file in "${{ steps.changed-files.outputs.changed_files }}"; do
              if [[ " ${{steps.all-schemas.outputs.all_schemas[*]}} " =~ " ${file} " ]]; then
                  echo "found_dupes='true'" >> GITHUB_OUTPUT
              fi
          done;
        shell:
          bash
      - name: Comment PR Found
        uses: thollander/actions-comment-pull-request@v2
        if: steps.find-dupes.outputs.found_dupes == 'true'
        with:
          message: |
            :warning: Potentially found duplicate schema name!