name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Check-Schema-Uniqueness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Get changed files
        id: changed-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
              echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          else
              echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          fi
      - name: List files in the repository
        id: all-schemas
        run: |
          echo "all_schemas=$(find schema -type f -exec basename {} \; | xargs) >> $GITHUB_OUTPUT
          echo $all_schemas
      - name: Find dupes
        id: find-dupes
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
              if [[ " ${steps.all-schemas.outputs.all_schemas[*]} " =~ " ${file} " ]]; then
                  echo "found_dupes='true'" >> $FOUND_DUPES
          done
      - name: Comment PR Found
        uses: thollander/actions-comment-pull-request@v2
        if: steps.find-dupes.outputs.found_dupes == 'true'
        with:
          message: |
            :warning: Potentially found duplicate schema name!