name: Schemas Should Be Unique
on: pull_request
jobs:
  CheckSchemaUniqueness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get dupes
        id: dupes
        run: |
          echo "found_dupes=$(find schema ! -empty -type f -exec basename {} \; -exec sh -c 'md5sum "$1"' _ {} \; | sort | uniq -dD | xargs)" >> $GITHUB_OUTPUT
        shell:
          bash
      - name: Get changed files
        id: changed-files
        uses:
          tj-actions/changed-files@v37
        with:
          files: schema/**
      - name: Check filename matches schemaname
        id: matches
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Comment PR Found
        uses: thollander/actions-comment-pull-request@v2
        if: steps.dupes.outputs.found_dupes
        with:
          message: |
            :warning: Duplicate schema names found in the repo
    
